### ISSUE TITLE
SMTP settings for Laravel 9+ are incorect

### ISSUE THREAD

**Issue by andreibaca** [mailcatch/issues#1]
It is now:
MAIL_HOST=sandbox-smtp.smtp.mailcatch.app

<img width="614" alt="image" src="https://github.com/mailcatch/issues/assets/75330721/0563499c-8170-438c-93e4-0de2a305f659">

and it should be:
MAIL_HOST=sandbox-smtp.mailcatch.app

Here is the error:
<img width="1098" alt="image" src="https://github.com/mailcatch/issues/assets/75330721/ebbfd86d-1857-42d9-8662-fa7926d1043d">

**Comment by lexor** [comment]
Nice catch! 🔥 It should be fixed now.
